# action.yml
name: "Hello World"
description: "Greet someone and record the time"
inputs:
  password: # id of input
    description: "sa password for sql"
    required: true
    default: "Y0uSh@llN0tP@ss"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.password }}
