using ClassLibrary1;
using System;
using System.Runtime.InteropServices;
using System.Text;

namespace ConsoleApp1
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var defaultMessage = "Hello from .NET Framework!";
            var bot = GetBot();
            var (message, withColor) = ParseArgs(args);
            var output = message == string.Empty ? $"    {defaultMessage}{bot}" : $"    {message}{bot}";

            if (withColor)
            {
                ConsoleUtils.PrintStringWithRandomColor(output);
            }
            else
            {
                Console.WriteLine(output);
            }

            Console.WriteLine("**Environment**");
            Console.WriteLine($"Platform: .NET Framework");
            Console.WriteLine($"OS: {RuntimeInformation.OSDescription}");
            Console.WriteLine();
        }

        private static (string, bool) ParseArgs(string[] args)
        {
            var buffer = new StringBuilder();
            var withColor = false;
            foreach (var s in args)
            {
                if (s == "--with-color")
                {
                    withColor = true;
                    continue;
                }
                buffer.Append(" ");
                buffer.Append(s);
            }

            return (buffer.ToString(), withColor);
        }

        private static string GetBot()
        {
            return @"
      __________________
                        \
                        \
                            ....
                            ....'
                            ....
                          ..........
                      .............'..'..
                  ................'..'.....
                .......'..........'..'..'....
                ........'..........'..'..'.....
              .'....'..'..........'..'.......'.
              .'..................'...   ......
              .  ......'.........         .....
              .                           ......
              ..    .            ..        ......
            ....       .                 .......
            ......  .......          ............
              ................  ......................
              ........................'................
            ......................'..'......    .......
          .........................'..'.....       .......
      ........    ..'.............'..'....      ..........
    ..'..'...      ...............'.......      ..........
    ...'......     ...... ..........  ......         .......
  ...........   .......              ........        ......
  .......        '...'.'.              '.'.'.'         ....
  .......       .....'..               ..'.....
    ..       ..........               ..'........
            ............               ..............
          .............               '..............
          ...........'..              .'.'............
        ...............              .'.'.............
        .............'..               ..'..'...........
        ...............                 .'..............
        .........                        ..............
          .....

  ";
        }
    }
}