on: [push]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker build --file=Dockerfile -t hello-image .
